💄(grafana) change default theme to light
openfun/potsie pull request #58
Opened 2022-05-05 17:09 UTC by quitterie-lcs

By default, the change theme is set to dark. But for random users, the
default theme has to be set to light.

## Purpose

Description...

## Proposal

Description...

- [ ] item 1...
- [ ] item 2...

2022-05-13 08:44 UTC, jmaupetit requested changes
I think you must remove the post-deploy hook script but restore the hooks feature.

2022-05-18 09:09 UTC, jmaupetit reviewed
Great! I suggest few interface improvements :muscle:

2022-05-18 13:58 UTC, quitterie-lcs commented on CHANGELOG.md
> +- Predefined dashboard uids
I would keep this in the `added` section as there was no pre-definition before ? WDYT?

2022-05-18 14:33 UTC, jmaupetit commented on CHANGELOG.md
> +- Predefined dashboard uids
Do as you please.

2022-05-18 14:37 UTC, jmaupetit approved these changes
<img src="https://media4.giphy.com/media/dkGhBWE3SyzXW/giphy.gif"/>

2022-05-18 14:45 UTC, merged